### ISSUE TITLE
How to obtain a user access key

### ISSUE THREAD

**Issue by iMezouar** [linux-dash/cli#1]
I'm trying to get a user access key in order to use the linux-dash cli, but the page at http://linuxdash.afaqtariq.com/ only shows a linux dash demo (it seems), and there is no way to get a key. Could you please look into this ?
Thanks !

**Comment by afaqurk** [comment]
Please go to afaqurk/linux-dash . this repo is not the Linux Dash project but something else.

**Comment by iMezouar** [comment]
Thanks for your quick reply, but this is the repo for Linux Dash cli, is it not ?
I'm trying to install linux dash via npm, to manage the Linux Dash monitoring agent, and in your instructions you say a User Access Key needs to be obtained from your page at linuxdash.afaqtariq.com, but it only shows a linux dash demo.
Thanks for your help.
